require("andm.plugins-setup")
require("andm.core.options")
require("andm.core.keymaps")
require("andm.core.colorscheme")
require("andm.plugins.nvim-tree")
require("andm.plugins.lualine")
require("andm.plugins.lsp.mason")
